# Generated by Django 3.2 on 2021-05-04 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pollquetions',
            old_name='pollquetions',
            new_name='pollquetion',
        ),
    ]
