# Generated by Django 3.2 on 2021-05-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_pollquetions_pollquetions_pollquetion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollquetions',
            name='pollquetion',
            field=models.CharField(max_length=20),
        ),
    ]
